export const EXPAND_MENU = 'EXPAND_MENU'

export const SELECT_MENU = 'SELECT_MENU'

export const SELECT_CANVAS = 'SELECT_CANVAS'

export const SET_SHOW_TAGS = 'SET_SHOW_TAGS'

export const SHOW_TAGS_MENU_TOGGLE = 'SHOW_TAGS_MENU_TOGGLE'

export const SHOW_ANALYSIS_REPORT_POPUP = 'SHOW_ANALYSIS_REPORT_POPUP'

export const SEGMENTATION_VISIBLE_TOGGLE = 'SEGMENTATION_VISIBLE_TOGGLE'

export const SEGMENTATION_SELECTED_TOGGLE = 'SEGMENTATION_SELECTED_TOGGLE'

export const SEGMENTATION_TOGGLE_ALL = 'SEGMENTATION_TOGGLE_ALL'

export const SET_CAPTURED_IMAGE = 'SET_CAPTURED_IMAGE'

export const SET_CHART_REPORTS = 'SET_CHART_REPORTS'

export const SET_REPORT = 'SET_REPORT'

export const SET_TAG_INFO = 'SET_TAG_INFO'

export const SET_MASK_OPACITY = 'SET_MASK_OPACITY'
