export const MENU_CLICKED = 'MENU_CLICKED'

export const FILE_UPLOADED = 'FILE_UPLOADED'

export const FILE_UPLOADED_SEG = 'FILE_UPLOADED_SEG'

export const SHOW_SEGMENTATION_POPUP = 'SHOW_SEGMENTATION_POPUP'

export const SHOW_ANALYSIS_REPORT_POPUP = 'SHOW_ANALYSIS_REPORT_POPUP'

export const SHOW_MASK_OPACITY_POPUP = 'SHOW_MASK_OPACITY_POPUP'

export const MASK_OPACITY_CHANGED = 'MASK_OPACITY_CHANGED'

export const SET_MASK_VISIBILITY = 'SET_MASK_VISIBILITY'

export const SHOW_HELP_POPUP = 'SHOW_HELP_POPUP'

export const FLIP_HORIZONTAL = 'FLIP_HORIZONTAL'

export const RESET_TAG_INFO = 'RESET_TAG_INFO'
